# site settings
title: Emma & Jaidev
subtitle: subtitle
email: site@jdem.com.au
description: Emma & Jaidev Vasudevans' site
baseurl:  # the subpath of your site, e.g. /blog
url:  # the base hostname & protocol for your site
author: Emma & Jaidev Vasudevan
street_address: 
city: Brisbane
state: Queensland
zip_code: 
country: Australia
phone:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 7

# social settings
500px_url:
facebook_url:
github_url: https://github.com/thejdev
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
